import PdfPrinter from 'pdfmake'
import type { TDocumentDefinitions } from 'pdfmake/interfaces'
import { brandLogoDataUrl } from './brand'
import { computeTotals, formatInr } from './totals'

const fonts = {
  Helvetica: {
    normal:      'Helvetica',
    bold:        'Helvetica-Bold',
    italics:     'Helvetica-Oblique',
    bolditalics: 'Helvetica-BoldOblique'
  }
}
const printer = new PdfPrinter(fonts)

interface QuotationForPdf {
  title: string
  customer: string | null
  discount_pct: number
  gst_pct: number
  freight: number
  notes?: string | null
  payment_terms?: string | null
  delivery_terms?: string | null
  validity?: string | null
  revision_no?: number | null
  items: Array<{
    line_no: number
    description: string
    sku: string | null
    unit: string | null
    vendor: string | null
    qty: number
    unit_price: number
  }>
}

export async function renderQuotationPdf(q: QuotationForPdf): Promise<Buffer> {
  const totals = computeTotals(q.items, q)
  const logo = brandLogoDataUrl()

  const body: any[][] = [
    [
      { text: '#',           style: 'th' },
      { text: 'Description', style: 'th' },
      { text: 'SKU',         style: 'th' },
      { text: 'Unit',        style: 'th' },
      { text: 'Vendor',      style: 'th' },
      { text: 'Qty',         style: 'th', alignment: 'right' },
      { text: 'Rate',        style: 'th', alignment: 'right' },
      { text: 'Amount',      style: 'th', alignment: 'right' }
    ],
    ...q.items.map(i => ([
      String(i.line_no),
      i.description,
      i.sku  ?? '',
      i.unit ?? '',
      i.vendor ?? '',
      { text: String(i.qty),               alignment: 'right' },
      { text: formatInr(Number(i.unit_price)), alignment: 'right' },
      { text: formatInr(Number(i.qty) * Number(i.unit_price)), alignment: 'right' }
    ]))
  ]

  const def: TDocumentDefinitions = {
    pageSize: 'A4',
    pageMargins: [36, 48, 36, 48],
    defaultStyle: { font: 'Helvetica', fontSize: 9 },
    content: [
      {
        columns: [
          {
            width: 54,
            stack: [
              logo
                ? { image: logo, width: 44 }
                : { text: 'RJ', style: 'logoFallback' }
            ]
          },
          {
            width: '*',
            stack: [
              { text: 'Proforma Invoice', style: 'h1' },
              { text: q.title, style: 'h2' },
              q.customer ? { text: `Customer: ${q.customer}`, color: '#555' } : { text: '' },
              { text: `Revision: ${q.revision_no ?? 1}`, color: '#555' }
            ]
          }
        ],
        margin: [0, 0, 0, 16]
      },
      {
        table: {
          headerRows: 1,
          widths: [16, '*', 60, 40, 60, 30, 50, 60],
          body
        },
        layout: 'lightHorizontalLines'
      },
      {
        margin: [0, 16, 0, 0],
        columns: [
          {
            width: '*',
            stack: [
              q.validity ? { text: `Validity: ${q.validity}` } : { text: '' },
              q.payment_terms ? { text: `Payment terms: ${q.payment_terms}` } : { text: '' },
              q.delivery_terms ? { text: `Delivery terms: ${q.delivery_terms}` } : { text: '' },
              q.notes ? { text: `Notes: ${q.notes}`, margin: [0, 8, 0, 0] } : { text: '' }
            ]
          },
          {
            width: 220,
            table: {
              widths: ['*', 'auto'],
              body: [
                ['Subtotal',                   { text: formatInr(totals.subtotal), alignment: 'right' }],
                [`Discount (${q.discount_pct}%)`, { text: '-' + formatInr(totals.discount), alignment: 'right' }],
                [`GST (${q.gst_pct}%)`,        { text: formatInr(totals.gst), alignment: 'right' }],
                ['Freight',                    { text: formatInr(totals.freight), alignment: 'right' }],
                [{ text: 'Grand total', bold: true }, { text: formatInr(totals.grand_total), alignment: 'right', bold: true }]
              ]
            },
            layout: 'noBorders'
          }
        ]
      },
      { text: 'Prices subject to verification. Generated by AI Ratefinder.', italics: true, fontSize: 8, margin: [0, 24, 0, 0] }
    ],
    styles: {
      h1: { fontSize: 18, bold: true, margin: [0, 0, 0, 4] },
      h2: { fontSize: 12, color: '#555', margin: [0, 0, 0, 12] },
      logoFallback: { fontSize: 18, bold: true, color: '#333', margin: [0, 4, 0, 0] },
      th: { bold: true, fillColor: '#f4f4f5' }
    }
  }

  return new Promise<Buffer>((resolve, reject) => {
    const doc = printer.createPdfKitDocument(def)
    const chunks: Buffer[] = []
    doc.on('data', (c: Buffer) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)
    doc.end()
  })
}
